service: sls-stack

provider:
  name: aws
  runtime: nodejs8.10
  deploymentBucket: nodelabs-deploy

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: any

  func1:
    handler: handler.func1
    events:
      - http:
          path: func1/{value1}/{value2}
          method: any

  func2:
    handler: handler.func2
    events:
      - http:
          path: func2/{value1}/{value2}
          method: any
          integration: lambda
