service: sls-stack

provider:
  name: aws
  runtime: nodejs8.10
  deploymentBucket: nodelabs-deploy

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: any
